# Development override for docker-compose.yml
# This file extends the base docker-compose.yml for development usage
# Use: docker-compose -f docker-compose.yml -f docker-compose.override.yml up

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    ports:
      - "3000:5000"
      - "5173:5173"  # Vite dev server
    
  database:
    ports:
      - "5432:5432"  # Expose database port for development tools