version: '3.8'

services:
  # PostgreSQL Database
  database:
    image: postgres:15-alpine
    container_name: biggs-permit-db
    environment:
      POSTGRES_DB: biggs_permit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - biggs-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d biggs_permit"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Main Application
  app:
    build: .
    container_name: biggs-permit-app
    ports:
      - "3000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/biggs_permit
      - PGHOST=database
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=biggs_permit
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
      - app_node_modules:/app/node_modules
    networks:
      - biggs-network
    restart: unless-stopped


volumes:
  postgres_data:
  app_node_modules:

networks:
  biggs-network:
    driver: bridge